### ISSUE TITLE
Service connection:Missing Machine Learning Workspace

### ISSUE THREAD

**Issue by fhe-fr** [microsoft/MLOpsPython#105]
I installed the New MLOps (DevOps for Machine Learning) from marketplace. But when I create a service connection there is no place to specify "Machine Learning Workspace"

**Comment by algattik** [comment]
This is now here, created #109 as the Wizard UI has changed
<img width="477" alt="image" src="https://user-images.githubusercontent.com/22099722/69495756-b28d2a80-0eca-11ea-83e9-0b14cc4e95bd.png">
