### ISSUE TITLE
Hyperparameter a pipeline parameter, not random value

### ISSUE THREAD

**Issue by algattik** [microsoft/MLOpsPython#107]
`MLOpsPython/code/training/train.py` picks a hyperparameter value randomly. This is an antipattern in 2 ways: (1) DevOps processes should yield reproducible outputs, (2) hyperparameters should be an AML pipeline parameter.

```
# Randomly pic alpha
alphas = np.arange(0.0, 1.0, 0.05)
alpha = alphas[np.random.choice(alphas.shape[0], 1, replace=False)][0]
```

**Comment by dtzar** [comment]
Yes, this is done for demo purposes to display something interesting on the metrics visuals.  Real customer code would of course not do this.

**Comment by algattik** [comment]
As this repo is a starting point for MLOps projects, it would be great to show best practice in code right away.

How about making the hyperparameter value a pipeline parameter, and generating a random value for it in the devops pipeline?

**Comment by dtzar** [comment]
sure.  PRs welcome.
