### ISSUE TITLE
Hardcoded run_id in python file

### ISSUE THREAD

**Issue by algattik** [microsoft/MLOpsPython#108]
https://github.com/microsoft/MLOpsPython/blob/6c56eeee14703dfb56d05941c1944c0d7d7116f2/code/register/register_model.py#L66
```
        run_id = "bd184a18-2ac8-4951-8e78-e290bef3b012"
```

**Comment by algattik** [comment]
Also in code/evaluate/evaluate_model.py

**Comment by alla15747** [comment]
run_id = "57fee47f-5ae8-441c-bc0c-d4c371f32d70"
Why do you add the run_id that you have to your experiment? Can't we read it automatically?
