### ISSUE TITLE
Evaluate Model should not fail the pipeline

### ISSUE THREAD

**Issue by algattik** [microsoft/MLOpsPython#115]
According to README.md
```If the new model performs better than the production model, the following steps are executed. If not, they will be skipped.```

That is not the behavior implemented today, as `register_model.py --validate` sets an exit code if no model was registered for the run, the pipeline actually *fails* in that case.
https://github.com/microsoft/MLOpsPython/blob/d4a7633152c32335bb43209be3a7d84ff8f4ed0b/code/register/register_model.py#L118

Expected behavior:

If the new model does not performs better than the production model;
* new model is registered (as is today);
* the pipeline *should succeed, skipping further steps*.

**Comment by dtzar** [comment]
This is the logic by design.  If no new model is registered then the pipeline failing is a visual way to know there wasn't a new model registered.  This makes it easy now for upon success to continue onward with another pipeline.  The `--validate` switch is only run after the pipeline completes.

**Comment by algattik** [comment]
The logic is predicated on the fact that the Azure ML extension *cancels* the pipeline if the ML Pipeline job gets canceled (which the pipeline does in the evaluate step, if the model performs no better than the previous one).

So, if using the extension to trigger the job (as the provided build pipeline does), the pipeline will be *canceled* (not *failed*) in that scenario. This is coherent.

**Comment by algattik** [comment]
Still, in that scenario the Azure DevOps pipeline is canceled but there is no message about why. A message at in the extension output stating "Canceling Azure DevOps pipeline as Azure ML pipeline run was canceled" would greatly help users.

**Comment by dtzar** [comment]
If the pipeline cancels or fails in the previous step, then the `--validate` script/job should fail the pipeline.  It is a safety/extra measure in place to ensure the model is actually registered before proceeding to deploy that model.  Also useful for people who may not want or cannot (i.e. non Azure DevOps) use the Azure ML agentless task.
