### ISSUE TITLE
Release pipeline ended successfully but there is no image generated

### ISSUE THREAD

**Issue by fhe-fr** [microsoft/MLOpsPython#120]
The release pipe line is ended correctly but there is no image created.
I have some errors and 3 warnings:
**Errors:**
1)2019-11-28T11:30:06.7605145Z [command]/usr/bin/az ml -h
2019-11-28T11:30:13.1124946Z ERROR: az: 'ml' is not in the 'az' command group. See 'az --help'.
2019-11-28T11:30:13.1125915Z No AzureML CLI installed.
2019-11-28T11:30:13.1129469Z [command]/usr/bin/az extension add -n azure-cli-ml
2019-11-28T11:30:40.6240864Z [command]/usr/bin/az ml -h
**Warnings:**
1) 2019-11-28T11:30:06.7593936Z ##[warning]Resource file haven\'t set, can\'t find loc string for key: AmlCliNotAvailable
2) 2019-11-28T11:30:44.8307996Z ##[warning]Resource file haven\'t set, can\'t find loc string for key: LoginFailed
3)2019-11-28T11:30:46.1742081Z ##[warning]Resource file haven\'t set, can\'t find loc string for key: ErrorInSettingUpSubscription

**Comment by algattik** [comment]
If you're deploying to ACI/AKS, you don't need to build an *Image*. You build a *Model* from which *Deployments* are directly generated (AML builds and provisions the image behind the scenes).

If you're deploying to Webapp (App Service for Containers) or some other place, you build an *Image* in ACR from the *Model* and then pull it.

**Comment by fhe-fr** [comment]
In my case a container is created and a scoring URL is associated to the ACI (pointing to the score file) but there is no model or image associated to this container.
