### ISSUE TITLE
Can this be parameterized by the service connection?

### ISSUE THREAD

**Issue by anisnouri** [microsoft/MLOpsPython#124]
Hey,
Wondering if the following subscription parameter is actually referring to WORKSPACE_SVC_CONNECTION variable?

https://github.com/microsoft/MLOpsPython/blob/2a22e75cd961af0995c3651138750a905e326935/environment_setup/iac-create-environment.yml#L26

**Comment by eedorenko** [comment]
No, it's not. AzureResourceConnection is a subscription level connection used to create required Azure resources for the repo sample.
