### ISSUE TITLE
Error during Azure ML Model Deploy

### ISSUE THREAD

**Issue by lahlfors** [microsoft/MLOpsPython#127]
Got the following error message:
 stderr: 'ERROR: {\'Azure-cli-ml Version\': \'1.0.79\', \'Error\': WebserviceException:\n\tMessage: Service deployment polling reached non-successful terminal state, current service state: Failed\nMore information can be found using \'.get_logs()\'\nError:\n{\n  "code": "AciDeploymentFailed",\n  "message": "Aci Deployment failed with exception: Your container application crashed. This may be caused by errors in your scoring file\'s init() function.\\n

**Comment by algattik** [comment]
#126 should fix this short-term
