### ISSUE TITLE
AML CLI not available

### ISSUE THREAD

**Issue by LauraVDS** [microsoft/MLOpsPython#130]
First: thank you very much for this repo. I like it a lot :)

However, I must be doing something wrong. At the 'Azure ML Model Deploy' task I keep getting the error:

Current Working Directory :  /__w/1/s/code/scoring
##[warning]Resource file haven\'t set, can\'t find loc string for key: AmlCliNotAvailable
[command]/usr/local/bin/az ml -h
ERROR: az: 'ml' is not in the 'az' command group. See 'az --help'.

And unfortunately the link with help (https://marketplace.visualstudio.com/items?itemName=ms-air-aiagility.private-vss-services-azureml&ssr=false#overview) seems not to work. Can someone point me to what I am missing? I do have the ML extension installed.

**Comment by eedorenko** [comment]
Just checked. The [link](https://marketplace.visualstudio.com/items?itemName=ms-air-aiagility.vss-services-azureml) works fine. So, yes you need to install that extension to follow the tutorial in this repo.

**Comment by LauraVDS** [comment]
Hi eedorenko,
thank you for having a look.

I meant the link to the description of task ms-air-aiagility.vss-services-azureml.azureml-model-deploy-task.AMLModelDeploy@0

I did install the Machine Learning extension and made a service connection using the Machine Learning extension (scope level: AzureMLWorkspace, WS name: the same as in WORKSPACE_SVC_CONNECTION and other fields filled in, too). However, I get this:
<img width="1066" alt="Screenshot 2019-12-19 at 08 59 03" src="https://user-images.githubusercontent.com/59024204/71155522-31615300-223e-11ea-8b05-98739f95204a.png">

**Comment by LauraVDS** [comment]
My bad, it was a capitalise in the name of the container instance. Now it runs smoothly.

**Comment by makautzn** [comment]
> My bad, it was a capitalise in the name of the container instance. Now it runs smoothly.

Hi @LauraVDS - I get the same error. Where exactly as your mistake?

**Comment by LauraVDS** [comment]
For me it was a capital in one of the resource names in the library - I don't recall which one exactly. Actually the error message I quote (ERROR: az: 'ml' is not in the 'az' command group. See 'az --help'.) is not the error that caused my problems, as the error is dealt with by the first few (blue) commands after the (white) error. The real error was further down in the terminal.
