### ISSUE TITLE
    (f"Unable to find a published pipeline for this build {e.build_id}")  # NOQA: E501

### ISSUE THREAD

**Issue by alla15747** [microsoft/MLOpsPython#135]
Generating script.
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /__w/_temp/898a4f68-c886-44f3-a349-df7a28a9d79f.sh
Traceback (most recent call last):
  File "/__w/1/s/ml_service/pipelines/run_train_pipeline.py", line 63, in <module>
    main()
  File "/__w/1/s/ml_service/pipelines/run_train_pipeline.py", line 38, in main
    raise KeyError(f"Unable to find a published pipeline for this build {e.build_id}")  # NOQA: E501
KeyError: 'Unable to find a published pipeline for this build 246'
/__w/_temp/898a4f68-c886-44f3-a349-df7a28a9d79f.sh: line 3: /__w/1/s/tmp.sh: No such file or directory
rm: cannot remove '/__w/1/s/tmp.sh': No such file or directory
##[error]Bash exited with code '1'.
Finishing: Get Pipeline ID

**Comment by LianaN** [comment]
I have the same issue. It works only when resources are created by running "iac-create-environment.yml" (not manually), and then "azdo-ci-build-train.yml" is executed. Any solution? Thanks.

**Comment by eedorenko** [comment]
Are you running the sample as it is or you have it modified (e.g. running with R or something)?

**Comment by eedorenko** [comment]
It looks like you work with an outdated version of the repo. The code doesn't correspond to the error message ("File "/__w/1/s/ml_service/pipelines/run_train_pipeline.py", line 38, in main")

**Comment by sudivate** [comment]
This issue is fixed with the new release.
