### ISSUE TITLE
Change model deployment AzDo pre-built task for Python SDK 

### ISSUE THREAD

**Issue by Anaig** [microsoft/MLOpsPython#136]
The ms-air-aiagility.vss-services-azureml.azureml-model-deploy-task.AMLModelDeploy@0 task in the  [azdo-ci-build-train](https://github.com/microsoft/MLOpsPython/blob/master/.pipelines/azdo-ci-build-train.yml ) is failing for AKS because the [compute_target_name](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.aks.aksservicedeploymentconfiguration?view=azure-ml-py) parameter is not correctly filled by the Azure CLI command. 

Using the Python SDK is providing a more stable and successful experience to deploy the model to a compute target.

Command produced by the task:
`az ml model deploy --ct akscomputetarget -n aks-name --model sklearn_model.pkl:1 --ic /__w/1/src/azureml/code/score/inference_config.json --dc /__w/1/src/azureml/code/score/deployment_config_aks.json -g rg-main -w aml-main --overwrite`

Error issued:
`ERROR: {\'Azure-cli-ml Version\': \'1.0.83\', \'Error\': MlCliError({\'Error\': \'Error parsing --deploy-config-file. Must be valid JSON or YAML file.\', \'Response Content\': TypeError("deploy_configuration() got an unexpected keyword argument \'compute_target_name\`

**Comment by gogowings** [comment]
This is due to the version mismatch between the azureml-core under cli directory HOME/.azure/cliextension/azure-cli-ml, and the one in virtual python env. To work around this right now, make sure you have the latest azureml-core in your venv (or conda). 

We are working on a long term solution.

**Comment by sudivate** [comment]
updated to latest azmlcore
