### ISSUE TITLE
Limitations of using shared mcr.microsoft.com/mlops/python:latest container

### ISSUE THREAD

**Issue by algattik** [microsoft/MLOpsPython#141]
* The steps for adapting the pipeline to use other ML modules than `scikit-learn` or additional Python modules besides pandas (provided in the sample `Dockerfile` and `requirements.txt`) are not obvious.
* While iterating on such ML modules or on their package versions, there is interference between branches when using `latest` repo tag. Similarly, there is a chicken-and-egg condition for PR checking on contributions to MLOpsPython with updating the `mcr.microsoft.com/mlops/python` base image.

Preparing a PR to propose a solution to the above.

**Comment by dtzar** [comment]
I believe this is covered now.
