### ISSUE TITLE
Pipeline should not be cancelled in the evaluation step

### ISSUE THREAD

**Issue by sbaidachni** [microsoft/MLOpsPython#151]
If evaluation doesn't show better results compare to the previous model, the pipeline cancels itself... It leads to auto-cancellation of Azure DevOps Build with no any particular reason that is really frustrating. At the same time, Build has own evaluation step that doesn't have any sense now.

Rather than cancel pipeline inside run we need to pass a parameter from evaluation to register model step. If no model has been register, the Evaluation pipeline in Azure DevOps Build will do its job

**Comment by algattik** [comment]
Agree, and this creates a problem for flow control. Typically a pipeline runs not in an isolated context but as part of a larger process.
