### ISSUE TITLE
tutorial getting started document - diabetes.csv data file missing link

### ISSUE THREAD

**Issue by CloudBreadPaPa** [microsoft/MLOpsPython#156]
Subject : tutorial getting started document - diabetes.csv data file missing link

Symptom : 404 page not found

Description : 
In [getting started tutorial](https://github.com/microsoft/MLOpsPython/blob/master/docs/getting_started.md) document, missing "diabetes.csv" link.

```
Note: The training ML pipeline uses a sample diabetes dataset as training data. If you want to use your own dataset, you need to create and register a datastore in your ML workspace and upload the datafile (e.g. diabetes.csv) ... 
```
diabetes.csv is linking to "https://github.com/microsoft/MLOpsPython/blob/master/data/diabetes.csv" link not "https://github.com/microsoft/MLOpsPython/blob/master/docs/data/diabetes.csv" this page.

**Comment by eedorenko** [comment]
The tutorial has been updated significantly.
