### ISSUE TITLE
How to use ACI?

### ISSUE THREAD

**Issue by afonya01** [microsoft/MLOpsPython#208]
Hi,

I'll get 3 containers ACI, according to guide. But I don't understand how to use trained model.

WebApp or Kubernetes were not deployed. Now I have only ACI. How to init requests to model and get response from it?

**Comment by gary918** [comment]
Go to Azure Machine Learning Studio(Preview) -> Endpoints -> Copy the address of REST Endpoint -> Pasted it to Chrome and append http://xxxxxxx.azurecontainer.io/score?data=[[1,2,3,4,5,6,7,8,9,10],[10,9,8,7,6,5,4,3,2,1]]

**Comment by sudivate** [comment]
Trained models after deploying to ACI or AKS can be accessed by web service endpoints. Follow the code snippet in [smoke_test_scoring_service.py](https://github.com/microsoft/MLOpsPython/blob/352ebbeba745ae1f421dddc7f36f81c4db766eee/ml_service/util/smoke_test_scoring_service.py#L15) that demonstrates how to invoke ML web service post-deployment.
