### ISSUE TITLE
Error when Pipeline runs more than 1 times

### ISSUE THREAD

**Issue by msgerneu** [microsoft/MLOpsPython#213]
I was able to configure the sample to run completly successfull until train model. After this, train model exits with

No Model found with {tag_name: BuildId ,tag_value: 8.}
Model was not registered for this run.
 ##[error]Script failed with error: Error: The process '/bin/bash' failed with exit code 1

in

Determine if evaluation succeeded and new model is registered

**Comment by jotaylo** [comment]
@msgerneu What was the outcome of the evaluation step in the ML pipeline? Out of the box, each run of the pipeline trains the same model, so it always evaluates to the same result. A new model is only registered if it evaluates as better than the previous result. You can use pipeline variables `RUN_EVALUATION` and `ALLOW_RUN_CANCEL` to control this behaviour - [details](https://github.com/microsoft/MLOpsPython/blob/56eb992991bb5755307abc0e5afe5d672f7c3764/.pipelines/diabetes_regression-variables.yml#L53)

**Comment by msgerneu** [comment]
thx for the hint.

    # Set to false to register the model regardless of the outcome of the evaluation step in the ML pipeline.
  # - name: ALLOW_RUN_CANCEL
  #   value: "true"

did it. i will close this
