### ISSUE TITLE
AKS Model Testing | Unauthorized, no Auth Header 

### ISSUE THREAD

**Issue by gdprtcl** [microsoft/MLOpsPython#227]
Hi,
I have deployed the Azure ML Model onto ACI and AKS.
I can pass in the inputs in for ACI, and get the scores back.

<img width="708" alt="Screenshot 2020-03-11 at 5 29 41 PM" src="https://user-images.githubusercontent.com/19777169/76414767-fa728780-63bd-11ea-850e-870a1d5861b9.png">

But for AKS, it says Unauthorized and requires an auth header. 

<img width="980" alt="Screenshot 2020-03-11 at 5 27 10 PM" src="https://user-images.githubusercontent.com/19777169/76414569-94860000-63bd-11ea-89a1-fcc78d81d22b.png">

What bearer token do I use? Else suggest a way out.

**Comment by dtzar** [comment]
You need to change [authentication to disabled here](https://github.com/microsoft/MLOpsPython/blob/58876338ed8b70699c75ad975662d4def5a84e71/diabetes_regression/scoring/deployment_config_aks.yml#L8)

**Comment by dtzar** [comment]
IMO we should disable SSL and authentication by default.  @sbaidachni if you'd like to keep these secure settings we should have it documented how to auth.

**Comment by gdprtcl** [comment]
@sbaidachni @dtzar It will be helpful to everyone if you can add the section to auth securely into the AKS deployment using the necessary keys and how one can retrieve them.

**Comment by sudivate** [comment]
When deploying to Azure Kubernetes Service, key-based authentication is enabled by default. You can also enable token-based authentication. Token-based authentication requires clients to use an Azure Active Directory account to request an authentication token, which is used to make requests to the deployed service. For more details on how to authenticate against the AKS service please follow the [documentation here](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-azure-kubernetes-service#web-service-authentication).

**Comment by sudivate** [comment]
updated get started doc with AKS auth details

**Comment by gdprtcl** [comment]
@sudivate @dtzar 
Thanks for mentioning about the smoke test as a reference on how to use service.get_keys(). 
One thing I would add: 
If we do an API call where the request needs the key, we can copy it from "**AML Workspace > Deployments > aks-deployment**" & paste it as the bearer token.
Here, we can see the primary and secondary key and regenerate them as well.
