### ISSUE TITLE
Alter score script and yml files for usage of multiple models

### ISSUE THREAD

**Issue by MichielMosmans** [microsoft/MLOpsPython#228]
How can we alter the scripts in order to use multiple models? I can't find any related question or documentation on this part and I am struggling to implement this by myself. My training script will generate a couple of hundred models. I would like to specify which models to use in the API calls and select the appropriate models by filename. 

service = Model.deploy(ws, aci_service_name, [my_model_1, my_model_2], inference_config, deployment_config)

I should probably do something similar as the statement above, but i do not know how to do this with the yml file as i can not find any documentation on altering the ms-air-aiagility.vss-services-azureml.azureml-restApi-task.MLPublishedPipelineRestAPITask@0 task to allow multiple endpoints.

Any help on this point would be much appreciated!

**Comment by gary918** [comment]
@MichielMosmans Would using multiple pipelines for training/deploying multiple models meet your requirement?
Or maybe you can implement your own task instead of using the existing one?

**Comment by gdprtcl** [comment]
@gary918 @MichielMosmans 
A quick question. 
Do we need separate pipelines for multiple models? Also, can we not have multiple deployment-endpoints on ACI and AKS. 
Eg. we can have /score for one /score2 for another.
