### ISSUE TITLE
Deploy MLOps resources to Azure:  policy violation allowed locations?

### ISSUE THREAD

**Issue by delbert** [microsoft/MLOpsPython#244]
hello folks,

i am running the first pipeline in the getting started section.

i am getting a series of policy violations in that pipeline run.  when i look up the policy, it says Allowed Locations, but it does not tell me which locations i am allowed to deploy to.

the error messages for the resources being deployed all follow this pattern (this is the first error message):

##[error]Resource 'mlopsbnamlsa' was disallowed by policy. Error Type: PolicyViolation, Policy Definition Name : Allowed locations, Policy Assignment Name : b3b13e998946aefb30ca7712d049fd0aa216c449de7321085f825a956699bf7e.

in my variable group, i have tried the following locations:  eastus, eastus2, centralus, and southcentralus.

do you know how i can look up the locations that i am allowed to deploy to?

i just created an AML workspace in eastus2, using the portal, so i am not sure what i am doing wrong.

thanks for any suggestions,
delbert

**Comment by j-so** [comment]
There may be a new policy over the subscription or resource group that you have created your workspace in.

You can use [az policy assignment show](https://docs.microsoft.com/en-us/cli/azure/policy/assignment?view=azure-cli-latest#az-policy-assignment-show) to see the list of allowed locations for the Policy Assignment Name you see in the error message.

**Comment by delbert** [comment]
thanks, j-so.  policy assignment show did the trick.  then i went to the policy assignment blade in the portal and removed the offending policy.
