### ISSUE TITLE
Deploying multiple models onto same ACI/AKS instance

### ISSUE THREAD

**Issue by gdprtcl** [microsoft/MLOpsPython#246]
Hi All,

Can anyone let me know what's the best practice to deploy multiple ML Models as per the MLOps framework?
I want to deploy the Models as isolated containers onto the same ACI / AKS instance.
If it is possible, how do we achieve that, assuming they will be running on the same host but accessible via different APIs?

**Comment by gdprtcl** [comment]
Current doing it with separate AKS Deployments being deployed onto each pod.

**Comment by salilbapat** [comment]
There are 2 options:
1) Deploy all models as part of the same service. In the Model.Deploy API, you can specify a list of models. But this would mean that you get a single endpoint to call into that service. And then in your script, you will have to look at the request and figure out which model to invoke.

2) Deploy models as separate services. So essentially call Model.Deploy for each model. Looks like you are already doing this. In this scenario, for AKS deployments, you can reuse any of the existing AKS clusters and deploy all these services to the same cluster. K8s will distrbute the pods amongst nodes in the cluster. So, you will get different endpoints for each model, and they will also be sharing the cluster. Currently there is no way to provide hints on how K8s can schedule these pods though. For ACI, these will get deployed as container services but will be on different nodes. There is no option in ACI so these different services will be hosted on same node (VM).

**Comment by gdprtcl** [comment]
Thanks @salilbapat for this.
