### ISSUE TITLE
Setting Keys with Model Deploy DevOps Task

### ISSUE THREAD

**Issue by gdprtcl** [microsoft/MLOpsPython#248]
Is there a way to set the primaryKey and secondaryKey as a part of the Azure ML Model Deploy task (Preview) while deploying onto AKS?

Setting it in the [deployment_config_aks.yml](https://github.com/microsoft/MLOpsPython/blob/master/diabetes_regression/scoring/deployment_config_aks.yml) works fine, but I want to specify it as an input parameter in the task in [diabetes_regression-ci.yml](https://github.com/microsoft/MLOpsPython/blob/27afdbb919690f1846aeddc45c44f0c206781a8d/.pipelines/diabetes_regression-ci.yml#L144)

Via CLI, az ml model deploy has "--kp" "--ks" parameters. So, I assume that there would be a way to do it if we are using the task.

**Comment by shivp950** [comment]
I would recommend using the cli moving forward for this, unfortunately the DevOps tasks have not been updated in a while to enable all the settings for deployments.
