### ISSUE TITLE
Suggestion: Add Terraform option to environment_setup

### ISSUE THREAD

**Issue by zoekdestep** [microsoft/MLOpsPython#251]
Hi! 

With the new Terraform module [azurerm_machine_learning_workspace](https://www.terraform.io/docs/providers/azurerm/r/machine_learning_workspace.html) (just released in the [v2.3.0 azurerm provider](https://github.com/terraform-providers/terraform-provider-azurerm/releases)), it would be great to add an iac-pipeline.yaml in environment_setup that uses Terraform to deploy the AML resources instead of ARM.

**Comment by fnocera** [comment]
@dtzar and @zoekdestep my team are looking into adding terraform scripts required for the repo.

**Comment by zoekdestep** [comment]
@fnocera we just implemented this for a customer, was planning on doing a PR tomorrow! :)

**Comment by fnocera** [comment]
@zoekdestep that sounds great! Did you also look into testing with terratest? We were thinking of exploring this and possibly contributing back.

**Comment by zoekdestep** [comment]
@fnocera we did not, that seems very interesting! Would be amazing to have that contributed back, our project could definitely learn from that!
