### ISSUE TITLE
Error during train model step in AML pipeline

### ISSUE THREAD

**Issue by dfay88** [microsoft/MLOpsPython#258]
I'm getting the following error during the train model step in the AML pipeline. 

Collecting azure
  Downloading azure-5.0.0.zip (4.6 kB)
[91m    ERROR: Command errored out with exit status 1:
     command: /azureml-envs/azureml_9e644656c33b3f7d66d071f83add673e/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2gno3lm3/azure/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2gno3lm3/azure/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-2gno3lm3/azure/pip-egg-info
         cwd: /tmp/pip-install-2gno3lm3/azure/
    Complete output (24 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2gno3lm3/azure/setup.py", line 60, in <module>
        raise RuntimeError(message)
    RuntimeError:
    
    Starting with v5.0.0, the 'azure' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.

Looks like you have to individually import each azure package used now. Can someone assist with updating the dependencies file located here with the necessary packages needed: diabetes_regression/conda_dependencies.yml

**Comment by mkhazen** [comment]
https://github.com/Azure/azure-sdk-for-python/issues/10646

**Comment by dfay88** [comment]
i fixed the issue by removing -azure from diabetes_regression/conda_dependencies.yml

**Comment by dfay88** [comment]
you will also need to re-run the IaC pipeline as it also uses that file

**Comment by mkhazen** [comment]
I have modified and deleted the -Azure from diabetes_regression/conda_dependencies.yml and then rerun the whole pipeline from CI but still same error 

- pip:
      # Required packages for AzureML execution, history, and data preparation.
      - azureml-model-management-sdk==1.0.1b6.post1
      - azureml-sdk==1.0.74
      - scipy==1.3.1
      - scikit-learn==0.22
      - pandas==0.25.3
      - numpy==1.17.3
      - joblib==0.14.0
      - gunicorn==19.9.0
      - flask==1.1.1
      - inference-schema[numpy-support]
      - azure-storage-blob
      - azureml-dataprep

**Comment by tcare** [comment]
@mkhazen can you try this commit? 03d1f907a0da1ab7a976e5841941f401721002c0

**Comment by dfay88** [comment]
you have to re-run the IaC pipeline as well before running the CI-CD pipeline. the conda dependency file is used while creating some of the infrastructure.

**Comment by tcare** [comment]
You can also try setting AML_REBUILD_ENVIRONMENT to true to stop caching

**Comment by mkhazen** [comment]
Still same issue - I deleted everything including my Resource Group on Azure, started from scratch  - used the new updated repository - and also on another run modified the file as was suggested in the commit  03d1f90 but still same error

**Comment by eedorenko** [comment]
Did you set AML_REBUILD_ENVIRONMENT to true?

**Comment by mkhazen** [comment]
I have added the AML rebuild environment - used the new master branch that was updated yesterday - I have deleted all of my resource group - rerun everything from scratch - still same error 

here is what I used that was commited yesterday 
name: diabetes_regression_training_env

dependencies:

  # The python interpreter version.

  # Currently Azure ML Workbench only supports 3.5.2 and later.

  - python=3.7.5

  # Required by azureml-defaults, installed separately through Conda to

  # get a prebuilt version and not require build tools for the install.

  - psutil=5.6 #latest



  - pip:

      # Required packages for AzureML execution, history, and data preparation.

      - azureml-model-management-sdk==1.0.1b6.post1

      - azureml-sdk==1.0.74

      - scipy==1.3.1

      - scikit-learn==0.22

      - pandas==0.25.3

      - numpy==1.17.3

      - joblib==0.14.0

      - gunicorn==19.9.0

      - flask==1.1.1

      - inference-schema[numpy-support]

      - azure-storage-blob

      - azureml-dataprep

**Comment by tcare** [comment]
Are you still seeing it try to download azure-5.0.0.zip?

Can you try my branch tcare/azure-meta-package

**Comment by eedorenko** [comment]
@mkhazen are you sure you see same error? You don't have "azure" dependency anymore and you see it still complaining on it?

**Comment by mkhazen** [comment]
it is working now - it was my mistake it was picking an old file - thank you for all of the support - as an FYI i have used this file[ 03d1f90]([url](https://github.com/microsoft/MLOpsPython/commit/03d1f907a0da1ab7a976e5841941f401721002c0))

But now there is another error under the deployment of the model

here is the error 

Command: az ml model deploy  -n mlopsm-aci --model diabetes_regression_model.pkl:1 --ic /__w/1/s/diabetes_regression/scoring/inference_config.yml --dc /__w/1/s/diabetes_regression/scoring/deployment_config_aci.yml -g mlopsm-RG -w mlopsm-AML-WS --overwrite

/usr/local/envs/mlopspython_ci/bin/az ml model deploy -n mlopsm-aci --model diabetes_regression_model.pkl:1 --ic /__w/1/s/diabetes_regression/scoring/inference_config.yml --dc /__w/1/s/diabetes_regression/scoring/deployment_config_aci.yml -g mlopsm-RG -w mlopsm-AML-WS --overwrite

Output:  

##[error]Error Code: [1]

ERROR: {'Azure-cli-ml Version': '1.2.0', 'Error': WebserviceException:

	Message: Service deployment polling reached non-successful terminal state, current service state: Unhealthy

Operation ID: 7c817965-ba94-47f3-bb97-6f3ba0953601

More information can be found using '.get_logs()'

Error:

{

  "code": "DeploymentTimedOut",

  "statusCode": 504,

  "message": "The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice."

}

	InnerException None

	ErrorResponse 

{

    "error": {

        "message": "Service deployment polling reached non-successful terminal state, current service state: Unhealthy\nOperation ID: 7c817965-ba94-47f3-bb97-6f3ba0953601\nMore information can be found using '.get_logs()'\nError:\n{\n  \"code\": \"DeploymentTimedOut\",\n  \"statusCode\": 504,\n  \"message\": \"The deployment operation polling has TimedOut. The service creation is taking longer than our normal time. We are still trying to achieve the desired state for the web service. Please check the webservice state for the current webservice health. You can run print(service.state) from the python SDK to retrieve the current state of the webservice.\"\n}"

    }

}}

##[error]Error: Failed to deploy model(s)

**Comment by eedorenko** [comment]
Closed with https://github.com/microsoft/MLOpsPython/pull/262
