### ISSUE TITLE
[Bug] Invoke ML pipeline failed without any output

### ISSUE THREAD

**Issue by yixwang** [microsoft/MLOpsPython#270]
Invoke ML pipeline failed without any output. Not sure where to start debugging. I am basically using the exactly same settings except the changes in the variables group

![image](https://user-images.githubusercontent.com/47333969/80178633-8f6ac200-85b3-11ea-84ed-996bc6375252.png)

**Comment by j-so** [comment]
Which release/commit are you using? Are you able to run the ML pipeline locally?

**Comment by yixwang** [comment]
@j-so, how do I check what release/commit I am using? I have not tried to run ML pipeline locally. Is it necessary?

**Comment by yixwang** [comment]
I see the error on the build main page:
![image](https://user-images.githubusercontent.com/47333969/80425624-e238c800-8898-11ea-8ebe-8191ea9ba8b6.png)

What is `https://.aether.ms/api`? The host name doesn't looks correct to me.

**Comment by yixwang** [comment]
nvm, the issue was the service connection didn't have right scope. It's fixed now.
