### ISSUE TITLE
Support rerunning evaluation step

### ISSUE THREAD

**Issue by epa095** [microsoft/MLOpsPython#273]
I have had the evaluation step canceled (because of low priority VM), and when I try to rerun it the python script crashes with 
```
Traceback (most recent call last):
  File "evaluate/evaluate_model.py", line 100, in <module>
    run_id = run.parent.id
AttributeError: 'NoneType' object has no attribute 'id'
```
It seems that the run-parent information is maybe not properly propagated through reruns? IDK.

**Comment by shivp950** [comment]
Where you able to work around this? We will try to reproduce this error on our end

**Comment by shivp950** [comment]
If there's no update, I'll go ahead and close this issue. Let us know if you run into any more bugs
