### ISSUE TITLE
Split the task in each job into smaller tasks

### ISSUE THREAD

**Issue by mydiemho** [microsoft/MLOpsPython#281]
Currently, the Model/Train/Deploy stages each consist of one job that has only one/two task(s) that does too many things.  It's really hard for user to debug when something goes wrong. 

Proposal:
1) Further split the task into smaller tasks that does smaller unit of work

Benefits:
1) This will be easier for AzDO beginner to map what they have been doing in previous challenges/jupyter to the pipeline structure
2) Easier to debug which step is broken
3) Help them understand what part takes the longest

**Comment by shivp950** [comment]
Thank you for the feedback, we'll look into breaking out the tasks.
