### ISSUE TITLE
Environment pipelines run on PRs

### ISSUE THREAD

**Issue by epa095** [microsoft/MLOpsPython#282]
The environment creation pipelines triggers on pull requests by default. Is this not quite weird? Seems to make more sense to change the environment the moment the PR is merged.

https://github.com/microsoft/MLOpsPython/blob/f8cd70f3b1e573bb859c5d49526032e412357bfc/environment_setup/iac-create-environment-pipeline-arm.yml#L9

**Comment by shivp950** [comment]
the pipeline yamls provide guidance but do not cover every scenario. You can change this in your own set up if you find it better to set the condition to post merge
