### ISSUE TITLE
build pipeline for custom docker image fails

### ISSUE THREAD

**Issue by benjaminbluhm** [microsoft/MLOpsPython#286]
Hi,

Needless to say this repo is super helpful!

I am running into an issue when creating a container build pipeline via Azure DevOps as described in [docs/custom_container.md](https://github.com/microsoft/MLOpsPython/blob/master/docs/custom_container.md).

For testing purposes, I did not modify the Dockerfile and I only changed the environment name in [environment_setup/docker-image-pipeline.yml](https://github.com/microsoft/MLOpsPython/blob/master/environment_setup/docker-image-pipeline.yml). When I run the pipeline, I get the following error:

```
##[error]invalid argument "***/mlops/my_env:amlsdk-$(amlsdkversion)" for "-t, --tag" flag: invalid reference format
##[error]See 'docker build --help'.
##[error]The process '/usr/bin/docker' failed with exit code 125
```

It seems to me that $(amlsdkversion) does not resolve as expected. Is there anything I am doing wrong here?

**Comment by j-so** [comment]
You will need to set `amlsdkversion` and `githubrelease` as pipeline variables on execution time (or saved under Edit->Variables). These are used in the tags for your image.

![image](https://user-images.githubusercontent.com/5027592/83808171-30e03b80-a669-11ea-9d92-26ee29c00a80.png)


This should get added to our docs.

**Comment by benjaminbluhm** [comment]
Thanks for clarifying this point. Adding this explanation to the docs would be good.
