### ISSUE TITLE
Docs for getting started is missing a step

### ISSUE THREAD

**Issue by leolorenzoluis** [microsoft/MLOpsPython#30]
Following https://github.com/MachineIearning/MLOpsPython/blob/master/docs/getting_started.md

For #5 Setup a build pipeline
It has missing steps on DevOps

I get the following error when I run the job

 

> There was a resource authorization issue: "The pipeline is not valid. Job Job: Step AzureCLI1 input connectedServiceNameARM references service connection build-demo which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.,Job Job: Step AzureCLI2 input connectedServiceNameARM references service connection build-demo which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."

**Comment by tamitarai** [comment]
Same problem has occured.
@leorenzoluis
Has the problem been solved?
