### ISSUE TITLE
Azure ML Studio

### ISSUE THREAD

**Issue by Taakn** [microsoft/MLOpsPython#300]
Hello,

I'm getting started here so this is more of a question, but how does this compare to Azure ML studio?

Thanks so much

**Comment by shivp950** [comment]
AzureML studio (which is the new UI) or Azure ML studio (classic)? Here's the documentation for classic - https://docs.microsoft.com/en-us/azure/machine-learning/compare-azure-ml-to-studio-classic


AML and DevOps work together, AML has a workspace boundary that tracks individual assets and artifacts. Devops provides the code and pipeline management. 

The AML studio is the new UI for Azure Machine Learning service.
