### ISSUE TITLE
Authorization issue at CI step

### ISSUE THREAD

**Issue by PurnaChandraPanda** [microsoft/MLOpsPython#301]
Following the [get started](https://github.com/microsoft/MLOpsPython/blob/master/docs/getting_started.md) doc, I set up my project as a devops project. However, it fails at [CI training](https://github.com/microsoft/MLOpsPython/blob/master/docs/getting_started.md#set-up-the-model-ci-training-evaluation-and-registration-pipeline) step. 

```
There was a resource authorization issue: "The pipeline is not valid. Job Model_CI_Pipeline: Step AzureCLI input connectedServiceNameARM references service connection aml-workspace-connection which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.,Job Get_Pipeline_ID: Step getpipelineid input connectedServiceNameARM references service connection aml-workspace-connection which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."
```

Can someone please guide what I am missing here? I am just trying to follow the doc as it is.

**Comment by j-so** [comment]
Do you see a service connection in your Azure DevOps project named "aml-workspace-connection" that you created earlier?

**Comment by PurnaChandraPanda** [comment]
@j-so  I see two service connections created on my devops project namely: 1) azure-resource-connection, 2) WORKSPACE_SVC_CONNECTION. On the variable group, it have variable named `WORKSPACE_SVC_CONNECTION` with value `aml-workspace-connection`. 

Error seems to be related to authorization. Is it like certain permission elements missing from AAD app level?

**Comment by j-so** [comment]
The name of your seconds service connection should be "aml-workspace-connection", instead of "WORKSPACE_SVC_CONNECTION".

The service connection should be all you need (you can find it in your workspace as an Owner role). The script expects it to be named "aml-workspace-connection".

**Comment by j-so** [comment]
Please reopen if you are still having this issue.
