### ISSUE TITLE
SCORING_DATASTORE_STORAGE_NAME, SCORING_DATASTORE_ACCESS_KEY are described as optional, but never covered 

### ISSUE THREAD

**Issue by cmayomsft** [microsoft/MLOpsPython#313]
In /docs/getting_started.md, the variables are listed as optional, but never covered in the doc re: when/how you'd use them.

I added them thinking it would be covered later and it caused an error the "Set up the Release Deployment and/or Batch Scoring pipelines".

![image](https://user-images.githubusercontent.com/3172553/87182817-b921b400-c299-11ea-9542-0efd0804ff1d.png)

**Comment by jplane** [comment]
+1 having the exact same issue... I want to setup batching scoring, so I:

- created a new storage account
- added the storage account name/key to the appropriate variables in the variable group (as outlined in the "getting started" guide
- even ensured the service principal used for my AzDO -> AML service connection is set as Contributor for the new storage account (the whole resource group, actually)

I get the same error in the same place as @cmayomsft 

![image](https://user-images.githubusercontent.com/3279259/87858957-c2e19200-c8ff-11ea-9733-622c598bd019.png)

It appears something is mis-configured and causing fallback to interactive Azure CLI authentication, which of course does not work very well in a CI build. :-)

What's odd is that the training pipeline seems to work fine... its unclear why.

**Comment by j-so** [comment]
There definitely needs to be more documentation about those environment variables. 

Will try to repro the issue.

**Comment by shivp950** [comment]
@jitghosh have you ran into this issue before? can you take a look?
