### ISSUE TITLE
AKS Deployment auto generated Application Insights URL is giving access denied exception

### ISSUE THREAD

**Issue by srijiths** [microsoft/MLOpsPython#318]
Hi Team,

Scenario
---------
When deploying a ML model to AKS, in the End point tab, you can see an Application Insights URL auto populated. But by default the URL is pointing to default Microsoft account (@microsoft), not the organization/individual account. Hence Access Denied.

Sample Application Insights URL from AKS Deployment
------------------------------------------------------------
https://portal.azure.com#@microsoft.onmicrosoft.com/resource/subscriptions/<SUB_ID>/resourcegroups/<RESOURCE_GRP>/providers/microsoft.insights/components/<APP_ID>

How to Resolve
----------------
If you simply remove @microsoft to my organization eg: @tavant in the above URL, then it works.

So i think when creating an Application Insights URL for ML deployment, you need to consider the current organization/individual account also.

Tagging @p-lekkala and @MercyPrasanna. If this issue does not belongs here , please feel free to move it.

Thanks,
Srijith

**Comment by chweems** [comment]
I don't have access to this project in order to assign to myself but a fix was submitted for this issue (outside of this project) and we should be able to close it.

**Comment by shivp950** [comment]
I'll go ahead and close this, feel free to open the issue again if it persists
