### ISSUE TITLE
AKS Deployment Swagger URI is giving "Swagger not found" Exception

### ISSUE THREAD

**Issue by srijiths** [microsoft/MLOpsPython#321]
Hi Team,

The Swagger URI which is getting created as part of AKS Deployment is wrong. When you access the URI, its always saying "Swagger not found".

Sample Swagger URI
----------------------
http://<IP_OF_AKS>/api/v1/service/sym-fast-aks/swagger.json

Tagging @p-lekkala @MercyPrasanna

Thanks,
Srijith

**Comment by j-so** [comment]
@srijiths Apologies for the late reply! Are you still seeing this issue?

**Comment by srijiths** [comment]
@j-so Yes, the issue still persists.

**Comment by j-so** [comment]
Are you using a custom scoring script, or are you seeing this when using the exact copy from this repo?

If you have written your own scoring script, can you send me your input and output schemas? Something like [this](https://github.com/microsoft/MLOpsPython/blob/31512d3d6ec25e64d4195939b0ac036ce74c9b1a/diabetes_regression/scoring/score.py#L50-L62).

Here's more information on how input and output schemas are used for swagger generation: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-advanced-entry-script#automatically-generate-a-swagger-schema

**Comment by srijiths** [comment]
@j-so I got the issue now. My bad, i havnt properly configured input and output schema in the custom scoring script. Thank You for pointing this. Closing this ticket.
