### ISSUE TITLE
FAILED: Deploy to Web App at "Create model package and set IMAGE_LOCATION variable" step

### ISSUE THREAD

**Issue by TrilochanK** [microsoft/MLOpsPython#323]
Hi Team,

I was trying to run the deployment pipeline and planning to deploy the model to Azure web app. But the pipeline was failing continuously at step "**Create model package and set IMAGE_LOCATION variable**" with error message as given below 
"##[error]{'Azure-cli-ml Version': '1.12.0', 'Error': TypeError('package() takes from 2 to 4 positional arguments but 6 were given')}"
Please find the screen shot for the same.
![image](https://user-images.githubusercontent.com/32562885/91183106-b1628580-e708-11ea-8d68-4efaf78ea66a.png)

The same azure ml package command was working fine in azure cloud shell.

Looking forward for a positive response.

**Comment by j-so** [comment]
In our ci_dependencies.yml file, we set the azureml SDK version to 1.6.*, which is incompatible with the newest version of the azureml CLI. I have updated the docker image to use azureml SDK version 1.13.*. I will make a PR as well.

If you are using a different image, you will want to make sure that your versions of the azureml SDK and CLI match.
