### ISSUE TITLE
Publish Batch Scoring Pipeline Issue

### ISSUE THREAD

**Issue by snapfisher** [microsoft/MLOpsPython#324]
I'm having a failure in the batch scoring pipeline.  I created the storage account and can access it, but it's looking for input/diabetes_scoring_input.csv.  I created the input container, but this csv is not in the repo.  How does it get there?  I'm unclear if this is a real problem or a documentation issue.

![csvmissing](https://user-images.githubusercontent.com/45605309/91500436-87889a80-e891-11ea-9a28-72f5eb0122e7.JPG)

**Comment by j-so** [comment]
@snapfisher This is a documentation issue and needs to be updated. Thank you for pointing this out.

You can use the [diabetes.csv](https://github.com/microsoft/MLOpsPython/blob/master/data/diabetes.csv) file in the `data` folder and import this to your storage account (in the `input` container) with the name `diabetes_scoring_input.csv`.
