### ISSUE TITLE
Pipeline Resource Input must be valid

### ISSUE THREAD

**Issue by tjeng** [microsoft/MLOpsPython#325]
Hi, I kept running into the error "Pipeline resource xxx Input must be valid" despite changing the name of my CI Pipeline and reflecting the same name in the cd.yml file. How should I resolve this issue?

![image](https://user-images.githubusercontent.com/29038197/91914910-33155e80-ec87-11ea-8fb8-6a0cf010176d.png)

**Comment by j-so** [comment]
Make sure that you are changing [line 20](https://github.com/microsoft/MLOpsPython/blob/master/.pipelines/diabetes_regression-cd.yml#L20), and **not** line 19. 

Are you running the CI pipeline successfully? Can you share a screenshot of the first part (~30 lines) of the cd.yml file?

**Comment by j-so** [comment]
@tjeng Please reopen if you are still having this issue. Thanks!
