### ISSUE TITLE
Deploy models after retraining

### ISSUE THREAD

**Issue by aubinmazet** [microsoft/MLOpsPython#337]
Hello, 

This template covers the case where training is triggered by a  code merge on master. But for a model in production, most re-training is triggered by new data or performance degradation. 
How do you deploy models when the AML pipeline has been triggered by a schedule or a data-based event? There is no CI linked to the training job. 
Can we imagine a specific CI that is triggered by events other than a merge code?

Thanks!

**Comment by shivp950** [comment]
You can further customize triggers through event grid, most azure services are integrated with it - https://docs.microsoft.com/en-us/azure/event-grid/overview. You can use something like a logic app to trigger Azure devops pipelines. Here I have an example with datadrift - https://docs.microsoft.com/en-us/azure/machine-learning/how-to-use-event-grid
