### ISSUE TITLE
Build Pipeline fails 

### ISSUE THREAD

**Issue by luoanabecher** [microsoft/MLOpsPython#340]
When running azdo-ci-build-train.yml, the error message is '' A task is missing. The pipeline references a task called 'ms-air-aiagility.vss-services-azureml.azureml-restApi-task.MLPublishedPipelineRestAPITask'' This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 0, job 'Run_ML_Pipeline', step ''.)'

I`ve checked and the tasks is specified in the yml file:
steps:
    - task: ms-air-aiagility.vss-services-azureml.azureml-restApi-task.MLPublishedPipelineRestAPITask@0

So what could be the problem? Thanks!

**Comment by j-so** [comment]
Can you try manually adding the task here? https://marketplace.visualstudio.com/items?itemName=ms-air-aiagility.vss-services-azureml

You may need to do this as a one-time installation for your organization.

**Comment by j-so** [comment]
Please reopen if you are still having this issue after installing the task. Thanks!
