### ISSUE TITLE
Explain concepts in getting_started.md 

### ISSUE THREAD

**Issue by swildermann** [microsoft/MLOpsPython#35]
I really like the getting started markdown. The documentation is really good and it worked well. 
Still it would be really helpful to explain the concepts of each step a bit more. 

What I would suggest is a short introduction in each section explaining this: 
- Why should I do this 
- What does it help me with 
- What do data scientists normally do if they do not do this step 
- A link explaining the concept behind that a bit more 

Also please divide it into multiple files with speaking names.

**Comment by marcelfranke** [comment]
Totally agree. Maybe we can integrate this into the Team Data Science Process https://docs.microsoft.com/en-us/azure/machine-learning/team-data-science-process/overview

**Comment by eedorenko** [comment]
Perhaps this article https://docs.microsoft.com/en-us/azure/machine-learning/tutorial-convert-ml-experiment-to-production#use-your-own-model-with-mlopspython-code-template (linked from Getting Started) answers your questions.

**Comment by sudivate** [comment]
Closing this as the new as we have new documentation
