### ISSUE TITLE
Deploy to AKS (CLI) times out

### ISSUE THREAD

**Issue by jknorvik** [microsoft/MLOpsPython#350]
Following the instructions in the getting started document everything worked well up to the Deploy the model to Azure Kubernetes Service step.  
I created a cluster on AKS , following the instructions on https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough-portal#create-an-aks-cluster, added the cluster to to Inference Compute in my my Azure ML workspace, and changed the variable group to include the AKS_COMPUTE_NAME and AKS_DEPLOYMENT_NAME, the latter to to the name of the Inference compute.
Then I started the pipeline and when it gets to the Deploy to AKS (CLI) step it times out.  The error message is _[error]Script failed with error: Error: The process '/bin/bash' failed with exit code 1_My guess is that the job cannot communicate with the AKS cluster, but I cannot figure out what configuration steps I have missed.  Any ideas?  
Attaching screen shots of the failed job log, the variable group, and the AKS cluster overview

![2021-02-11 (1)](https://user-images.githubusercontent.com/37778891/107677214-a7552480-6c5f-11eb-9a8b-c0075f2aa5af.png)
![2021-02-11 (2)](https://user-images.githubusercontent.com/37778891/107677217-a7edbb00-6c5f-11eb-8c93-75d1b5516835.png)
![2021-02-11](https://user-images.githubusercontent.com/37778891/107677222-a8865180-6c5f-11eb-9f93-9d43d5c637e2.png)

**Comment by felipeschneider88** [comment]
Hello, I'm facing the very same issue. This is the outcome of my error:


{"InvolvedObject":"mlops-aks-6c66c57f96-f9cfg","InvolvedKind":"Pod","Type":"Warning","Reason":"FailedScheduling","Message":"0/6 nodes are available: 1 Insufficient cpu, 2 pod has unbound immediate PersistentVolumeClaims, 4 Insufficient memory.","LastTimestamp":null}
{"InvolvedObject":"mlops-aks-6c66c57f96-f9cfg","InvolvedKind":"Pod","Type":"Normal","Reason":"Scheduled","Message":"Successfully assigned azureml-mlops-aml-ws/mlops-aks-6c66c57f96-f9cfg to aks-agentpool-22766417-vmss000003","LastTimestamp":null}
{"InvolvedObject":"mlops-aks-6c66c57f96-f9cfg","InvolvedKind":"Pod","Type":"Normal","Reason":"Pulled","Message":"Container image "mcr.microsoft.com/azureml/dependency-unpacker:20201117" already present on machine","LastTimestamp":"2021-03-01T14:06:01Z"}
{"InvolvedObject":"mlops-aks-6c66c57f96-f9cfg","InvolvedKind":"Pod","Type":"Normal","Reason":"Created","Message":"Created container amlappinit","LastTimestamp":"2021-03-01T14:06:02Z"}
{"InvolvedObject":"mlops-aks-6c66c57f96-f9cfg","InvolvedKind":"Pod","Type":"Normal","Reason":"Started","Message":"Started container amlappinit","LastTimestamp":"2021-03-01T14:06:02Z"}
{"InvolvedObject":"mlops-aks-6c66c57f96-f9cfg","InvolvedKind":"Pod","Type":"Normal","Reason":"Pulling","Message":"Pulling image "mlops001amlcr.azurecr.io/azureml/azureml_4fa77ac56481178e02c61e4c97fdf49a"","LastTimestamp":"2021-03-01T14:07:33Z"}
{"InvolvedObject":"mlops-aks-6c66c57f96-f9cfg","InvolvedKind":"Pod","Type":"Warning","Reason":"Failed","Message":"Failed to pull image "mlops001amlcr.azurecr.io/azureml/azureml_4fa77ac56481178e02c61e4c97fdf49a": rpc error: code = Unknown desc = Error response from daemon: Get https://mlops001amlcr.azurecr.io/v2/azureml/azureml_4fa77ac56481178e02c61e4c97fdf49a/manifests/latest: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.","LastTimestamp":"2021-03-01T14:07:33Z"}
{"InvolvedObject":"mlops-aks-6c66c57f96-f9cfg","InvolvedKind":"Pod","Type":"Warning","Reason":"Failed","Message":"Error: ErrImagePull","LastTimestamp":"2021-03-01T14:07:33Z"}
{"InvolvedObject":"mlops-aks-6c66c57f96-f9cfg","InvolvedKind":"Pod","Type":"Normal","Reason":"BackOff","Message":"Back-off pulling image "mlops001amlcr.azurecr.io/azureml/azureml_4fa77ac56481178e02c61e4c97fdf49a"","LastTimestamp":"2021-03-01T14:11:11Z"}
{"InvolvedObject":"mlops-aks-6c66c57f96-f9cfg","InvolvedKind":"Pod","Type":"Warning","Reason":"Failed","Message":"Error: ImagePullBackOff","LastTimestamp":"2021-03-01T14:21:12Z"}
"

It seams like there is an issue with the permission between AKS and ACR

**Comment by felipeschneider88** [comment]
Hello, I fixed with this command:
`az aks update -n myAKSCluster -g myResourceGroup --attach-acr`

Following this https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration#configure-acr-integration-for-existing-aks-clusters

**Comment by jknorvik** [comment]
I repeated all the steps in the Getting Started document and this time it worked
