### ISSUE TITLE
Bug: New PyJWT Version has breaking chances

### ISSUE THREAD

**Issue by oliverscheer** [microsoft/MLOpsPython#354]
The referenced PyJWT Library has been updated, and introduced breaking changes. 

You need to specify an older version in the files "conda_dependencies_scorecopy.yml" and "conda_dependencies_scoring.yml" to make the getting started tutorial work again. 

You need to add "PyJWT<2.0.0" to the pip section of both files.

**Comment by j-so** [comment]
Fixed by pinning AzureML sdk > 1.18 to get the fixed version.
