### ISSUE TITLE
How do I use jupyter notebooks with Azure MLOps

### ISSUE THREAD

**Issue by joshidp** [microsoft/MLOpsPython#371]
Hi,

How do I use jupyter notebooks with Azure MLOps?

In yaml what all steps do we need to modify?

Thanks

**Comment by arch-exe** [comment]
MOM, Can you Please, Please ask you co-workers, dog groomer, person that dose your taxes, neighbor, etc.. Looking for an Old Fix me upper VAN, preferably Cargo Van (There Cheap) but any van will do. Even a Car would work if that’s all that is available. We Can put 1000.00 down and make payments. PLEASE ASK EVERYONE YOU KNOW and contact me via email ***@***.***
We need help. Will be willing to work or do what ever it takes to get some form of transportation. Thanks in advance for your support!!


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
