### ISSUE TITLE
Unable to create service connection using a scope level of AzureMLWorkspace

### ISSUE THREAD

**Issue by KBaroni** [microsoft/MLOpsPython#56]
In Azure DevOps, I cannot create a service connection using the scope level of 'AzureMLWorkspace'.  The error generated suggests i don't have permission to add a role.   As a workaround, i manually created an SP and had my subscription admin provide it 'contributor' role access.   This approach also fails from the ADO side likely because the SP is not added as a user to the AML Workspace - and i don't have sufficient permissions as a 'contributor' to do so.  This is a blocker for using  Azure Model registration as an artifact for Azure DevOps and I have documented it on the ML Platform/AzureMLPython SDK teams channel.

**Comment by KBaroni** [comment]
Hi Eugene:

I have contributor level access in the azure subscription and am a project admin in the azure devops project.

This is the error I get when I try to create a service connection with AzureMLWorkspace scope:
A new Azure service principal will be created and assigned with the "Contributor" role, having access to all resources within the Workspace.
Failed to set Azure permission 'RoleAssignmentId: 597b3445-352a-41fc-9eca-4f5edf6c93ce' for the service principal '911b87e4-61ef-4f01-b496-f946dd9bb0ed' on machine learning workspace ID '510ebabd-4d14-45f9-8b2f-757fda448fcc': error code: Forbidden, inner error code: AuthorizationFailed, inner error message The client 'kbaroni@microsoft.com' with object id 'd51035f6-4a0d-4ba6-8363-6943dacbcf5b' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/subscriptions/bf7adf12-c3a8-426c-9976-29f145eba70f/resourceGroups/kbtest/providers/Microsoft.MachineLearningServices/workspaces/kbtest/providers/Microsoft.Authorization/roleAssignments/597b3445-352a-41fc-9eca-4f5edf6c93ce' or the scope is invalid. If access was recently granted, please refresh your credentials.

Ensure that the user has 'Owner' or 'User Access Administrator' permissions on the Workspace. For troubleshooting refer to link<https://go.microsoft.com/fwlink/?linkid=835898>.

**Comment by KBaroni** [comment]
I just had my azure admin add the SP as an ‘owner’ to the AML Workspace, and it still doesn’t work.

BTW, if owner level permissions is expected on the Azure subscription to execute this repo, that will be a significant blocker for any users with enterprise subscriptions.

**Comment by KBaroni** [comment]
It does not work with 'owner' permissions on AML Workspace only.   It works with owner permissions on RG - which can only be assigned by an azure subscription admin.

**Comment by eedorenko** [comment]
Thanks for confirming that. We'll add a note to the documentation that one should have **owner** permission on RG to create a service connection.

**Comment by sudivate** [comment]
@KBaroni  Please ensure you have owner or user admin access on the workspace. Most probably your contributor access from the subscription is inherited to the workspace. 
I have also updated doc with an explicit note on this.
