### ISSUE TITLE
Unable to execute QA (ACI) stage. Path name issue.  

### ISSUE THREAD

**Issue by KBaroni** [microsoft/MLOpsPython#58]
According to the get started document, there are 2 path variables that need to be configured for the **Azure ML Model Deploy** task in QA stage:
- Inference config path: $(System.DefaultWorkingDirectory)/_ci-build/mlops-pipelines/code/scoring/inference_config.yml
- Deployment config path: $(System.DefaultWorkingDirectory)/_ci-build/mlops-pipelines/code/scoring/deployment_config_aci.yml

After checking to make sure both training and QA pipeline are using ubuntu-16.04, execution fails with this message:   
 [error]ENOENT: no such file or directory, stat /home/vsts/work/r1/a/_ci-build/mlops-pipelines/code/scoring/deployment_config_aci.yml

In checking the logs for the training pipeline, this is where the files should have been downloaded to:    

- Downloaded mlops-pipelines/code/scoring/deployment_config_aci.yml to /home/vsts/work/r1/a/_ci-build/mlops-pipelines/code/scoring/deployment_config_aci.yml
- Downloaded mlops-pipelines/code/scoring/inference_config.yml to /home/vsts/work/r1/a/_ci-build/mlops-pipelines/code/scoring/inference_config.yml

So, i'm not sure why the execution is failing to find the files in the location.   Any suggestions?     

Thank you.

**Comment by KBaroni** [comment]
I have tried multiple ways to resolve this issue including, changing... 
- $(System.DefaultWorkingDirectory) to $(Build.ArtifactStagingDirectory)
- $(System.DefaultWorkingDirectory) to ./
- the name of the project

And consistently get the same error that there is **no such file /home/vsts/work/r1/a/_ci-build/mlops-pipelines/code/scoring/deployment_config_aci.yml.**   This is a blocker for me.

**Comment by KBaroni** [comment]
Resolution requires adding a 2nd artifact (which is not documented).  Once the repo is added as an artifact, path names can be selected from drop down.

**Comment by eedorenko** [comment]
**_ci-build** is the first artifact and It is documented in the **8. Deploy the Model** section:
"The pipeline consumes two artifacts: the result of the Build Pipeline as it contains configuration files and the model trained and registered by the ML training pipeline.

Configuration of a code _ci-build artifact is similar to what we did in the previous chapter."

And if the code artifact is aliased exactly as in the Getting Started (_ci-build), then the path parameters would be exactly as it is stated in the table **$(System.DefaultWorkingDirectory)/_ci-build/mlops-pipelines/code/scoring/inference_config.yml** and **$(System.DefaultWorkingDirectory)/_ci-build/mlops-pipelines/code/scoring/deployment_config_aci.yml**

**Comment by eedorenko** [comment]
So, I guess it should be closed.
