### ISSUE TITLE
Improve artifact end-to-end traceability

### ISSUE THREAD

**Issue by algattik** [microsoft/MLOpsPython#72]
Configuration management best practices demand there should be full traceability end-to-end from source code, build, release (model building & model deployment), as well as artifacts (model, container, pipeline runs etc.)

At this time there are gaps in achieving this, especially if concurrent builds are run, e.g.:
- the model deployment pipeline picks up the latest build
- the evaluate_model.py script assumes as described a comment: "Get most recently registered model, we assume that is the model in production"
- When traceability is possible, things are quite buried and require a lot of scripting to surface

**Comment by dtzar** [comment]
IMO at this point in time if someone does this it should close out this item:

1. Have the URL to the log output in Azure DevOps of the azure portal experiment run so someone from Azure DevOps can easily click to get more details on the experiment running associated with the build.
1. Tag the experiment runs in the Azure ML pipeline with the URL of the Azure DevOps build to get the bigger picture.
