### ISSUE TITLE
Include realistic test scenarios

### ISSUE THREAD

**Issue by algattik** [microsoft/MLOpsPython#74]
The template should include realistic test scenarios, in order to illustrate a proper test strategy and help deal with technical aspects (e.g. folder organization for pytest).
- Unit tests - the current code_test.py doesn't test the actual code in code/, including mocks
- Integration tests if applicable (e.g. connectivity to data marts)
- Smoke test of the deployed ACI container in staging before deploying to AKS

**Comment by dtzar** [comment]
@algattik Considering you updated unit test space and added the smoke test and there is no data integration test (i.e. due to lack of #75) - would it be fair to you to close this item out now?  Could add a separate issue for the data integration tests once 75 is implemented.

**Comment by algattik** [comment]
Agree, data connection related tests belong in #75.
