### ISSUE TITLE
This setup doesn't work with gitlab

### ISSUE THREAD

**Issue by triakki** [microsoft/MLOpsPython#76]
Hi, This setup doesn't seems to work with gitlab. can you please help by providing a sample or steps for the same

**Comment by dtzar** [comment]
Can you please provide more details as to where you get stuck?  Gitlab has not been tested here, but everything should be achievable there too with some creation of the pipelines there.

**Comment by dtzar** [comment]
Due to lack of response, closing.  Feel free to reopen if you'd like to engage.
