### ISSUE TITLE
Issue retrieving workspace

### ISSUE THREAD

**Issue by ToadTWP666** [microsoft/MLOpsPython#78]
I have recompleted this lab twice and had one of our senior CSAs check the config/setup for the workspace, service principal and library variable group. I am getting the following error when I execute the MLDevOps pipeline (please note replaced the TenentID in the error description with 'XXXXXXXXXXXXXXXX for security purposes):

ml_service/util/workspace.py:29: SystemExit
----------------------------- Captured stdout call -----------------------------
Error while retrieving Workspace...
Get Token request returned http error: 400 and server response: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'XXXXXXXXXXXXXXXX' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.\r\nTrace ID: 228b4b47-723d-41d1-a68c-77fffe8f2800\r\nCorrelation ID: 7121e3e3-ca7c-4f3d-b4f0-6280a935079a\r\nTimestamp: 2019-10-08 18:47:38Z","error_codes":[90002],"timestamp":"2019-10-08 18:47:38Z","trace_id":"228b4b47-723d-41d1-a68c-77fffe8f2800","correlation_id":"7121e3e3-ca7c-4f3d-b4f0-6280a935079a","error_uri":"https://login.microsoftonline.com/error?code=90002"}
=============================== warnings summary ===============================
/usr/local/lib/python3.7/site-packages/socks.py:58
  /usr/local/lib/python3.7/site-packages/socks.py:58: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Callable

/usr/local/lib/python3.7/site-packages/azureml/data/dataset_type_definitions.py:52
  /usr/local/lib/python3.7/site-packages/azureml/data/dataset_type_definitions.py:52: DeprecationWarning: FileType Enum is Deprecated in > 1.0.39. Use strings instead.
    category=DeprecationWarning)

/usr/local/lib/python3.7/site-packages/azureml/_base_sdk_common/utils.py:11
  /usr/local/lib/python3.7/site-packages/azureml/_base_sdk_common/utils.py:11: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Iterable

-- Docs: https://docs.pytest.org/en/latest/warnings.html
-------------- generated xml file: /__w/1/b/unit-testresults.xml ---------------
================ 1 failed, 4 passed, 3 warnings in 1.90 seconds ================
##[error]Bash exited with code '1'.
##[section]Finishing: Run unit tests

**Comment by eedorenko** [comment]
Did you create the environment for the repo with the IaC pipeline or manually? Can't recommend anything but checking again tenant/subscription/permissions.
