### ISSUE TITLE
Update the MLOps repo to use the new yml based multistage release process

### ISSUE THREAD

**Issue by md260** [microsoft/MLOpsPython#84]
The current MLOps repository showcases an older DevOps workflow where a user need to add task manually. The content of the repo should be updated to the “modern” way where all the steps can be specified in yml file.

**Comment by dtzar** [comment]
This is reasonable once we have build trigger artifacts in release - since we use this with the Azure ML task.

**Comment by dtzar** [comment]
With PR #101 and #90 we now no longer need to depend on the artifact trigger release via the Azure ML task since we'll know when a good model has been registered after a run.  Now it's possible to extend what's there into another stage for release.
