### ISSUE TITLE
Missing "save" step in MLOpsPython/docs/getting_started.md

### ISSUE THREAD

**Issue by ignaciofls** [microsoft/MLOpsPython#87]
I am missing a save step in this parragraph, before creating a new release. At least for me, the create release button is in gray and is not clickable until I save the release definitions

"This release pipeline should now be automatically triggered (continuous deployment) whenever a new ML training pipeline is published by the ci-build builder pipeline. It can also be triggered manually or configured to run on a scheduled basis. Create a new release to trigger the pipeline manually by clicking on the "Create release" button on the top right of your screen, when selecting this new build pipeline:"

**Comment by eedorenko** [comment]
Please, create a pull request with your vision of how the **getting_started.md** should be updated to make it clear.
