### ISSUE TITLE
Failed to Build the Pipeline?

### ISSUE THREAD

**Issue by alla15747** [microsoft/MLOpsPython#89]
##[section]Starting: Run code quality tests
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.151.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
flake8 --output-file=/__w/1/b/lint-testresults.xml --format junit-xml
========================== Starting Command Output ===========================
##[error]Bash exited with code '1'.
##[section]Finishing: Run code quality tests

**Comment by eedorenko** [comment]
Look at the **Test** tab of your build.
<img width="902" alt="Screen Shot 2019-11-08 at 1 49 26 PM" src="https://user-images.githubusercontent.com/20337555/68512965-ac425180-022e-11ea-8c21-f4612868cf4b.png">
