### ISSUE TITLE
   pytest --junitxm causes a fail in triggering the pipeline?

### ISSUE THREAD

**Issue by alla15747** [microsoft/MLOpsPython#92]
This command is causing a code error 127. And the pipelines fail to build.
I'm using windows 10. 
I install the latest version of Pytest.
   
pytest --junitxml=$(Build.BinariesDirectory)/unit-testresults.xml $(Build.SourcesDirectory)/tests/unit

**Comment by dtzar** [comment]
Are you trying to run that exact command locally?  If so, it will fail because the $(Build.BinariesDirectory) is only understood by Azure DevOps.  Pytest is working fine locally.
